### ISSUE TITLE
Cascade Delete Poem

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#13]
When we have a Poem that is like by a user, we can't delet it. 
We need to provide a CASCAD Delete for the poems

**Comment by arnonrdp** [comment]
I added the following logic to SQL:

- When a poem is removed, all likes associated with it are also removed;
- When a user is removed:
  - All poems associated with that user are removed;
  - All likes associated with the user are removed;
  - All likes of all poems created by him are also removed
  
  @hermannleboss, please check if it is ok for you.

**Comment by hermannleboss** [comment]
@arnonrdp it's not working for me. 

When i try to remove a poem I like i stil have 500 error

**Comment by hermannleboss** [comment]
@arnonrdp try it directly in the frontend and check the difference in the backend.

**Comment by arnonrdp** [comment]
@hermannleboss, it is now fixed, can you please check again?

**Comment by hermannleboss** [comment]
Wonderful it's working
