### ISSUE TITLE
Enable Layer 8 for weve got poems

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#19]

**Comment by hermannleboss** [comment]
- [x] Get nonce
- [x] SIWE
- [x] Get Poem
- [ ] Get Poems with useFetch
- [ ] Add Poem
- [ ] Update Poem 
- [ ] EDIT poem
- [x] Edit user personal data

**Comment by stravid87** [comment]
> * [x]  Get nonce
> * [x]  SIWE
> * [x]  Get Poem
> * [ ]  Get Poems with useFetch
> * [ ]  Add Poem
> * [ ]  Update Poem
> * [ ]  EDIT poem
> * [x]  Edit user personal data

I'm loving this checklist.

**Comment by stravid87** [comment]
Check out @DeeStarks NPM upload. I haven't had a chance to try it / play with it myself but you may be able to get SIWE working with it. 'https://www.npmjs.com/package/l8interceptor'
