### ISSUE TITLE
Create SQL script that can be run with npm run *

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#21]
We need an esay way to run database update scripts

- [ ] Create Database
- [x] Create Schema

like symfony doctrine commande 

symfony console doctrine:database:create
symfony console doctrine:schema:create

**Comment by stravid87** [comment]
@hermannleboss check out the code at the bottom of this article. Is this what you are looking for? 
https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

It's not very long so I've actually just pasted it here:

`const { Client } = require('pg');

const pgclient = new Client({
    host: process.env.POSTGRES_HOST,
    port: process.env.POSTGRES_PORT,
    user: 'postgres',
    password: 'postgres',
    database: 'postgres'
});

pgclient.connect();

const table = 'CREATE TABLE student(id SERIAL PRIMARY KEY, firstName VARCHAR(40) NOT NULL, lastName VARCHAR(40) NOT NULL, age INT, address VARCHAR(80), email VARCHAR(40))'
const text = 'INSERT INTO student(firstname, lastname, age, address, email) VALUES($1, $2, $3, $4, $5) RETURNING *'
const values = ['Mona the', 'Octocat', 9, '88 Colin P Kelly Jr St, San Francisco, CA 94107, United States', 'octocat@github.com']

pgclient.query(table, (err, res) => {
    if (err) throw err
});

pgclient.query(text, values, (err, res) => {
    if (err) throw err
});

pgclient.query('SELECT * FROM student', (err, res) => {
    if (err) throw err
    console.log(err, res.rows) // Print the data in student table
    pgclient.end()
});
`

**Comment by hermannleboss** [comment]
https://github.com/globe-and-citizen/weve-got-poems/blob/develop/backend/src/script.js

@stravid87 I create this script to generate the database table. 

I can update it for seeding the table with data.

**Comment by hermannleboss** [comment]
But for the moment it can be used only on local with `npm run db:create-table`

The usage with github action can be donne when we need to test it in the CI/CD. But right now we don't have test so i think it's not nécessary. 


We can implement it for CNC portal.

**Comment by stravid87** [comment]
> npm run db:create-table

Ah good idea. You've got it hooked up to the package.json scripts. 
To make it work in Layer8, I had the initializations scripts run directly / hardcoded into the source code -- not the most elegant solution!
