### ISSUE TITLE
Online Version of layer not working

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#26]
When i use this link :    https://layer8devproxy.net/assets-v1/cdn/interceptor/index.local.jsi have this error

![image](https://github.com/globe-and-citizen/weve-got-poems/assets/28951070/cbb5d8d4-6468-4d5d-a5d6-04032cc466cc)

**Comment by arnonrdp** [comment]
Closed due to being stalled.
