### ISSUE TITLE
[Feature request] Create a /me route

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#4]
We need a way for the frontend to have the current authenticated user information.
With this we have two way of using it. 

When we need sommes informations about the current authenticate user, like his email, displayname and ID. 
When we need to check if the current token is stil vallide : We can juste call the endpoint and if we have a token error, we will know if it's valide or not

**Comment by arnonrdp** [comment]
@hermannleboss, instead of creating a new `/me` API, would it help if I included the name and email of the user in the JWT?

**Comment by arnonrdp** [comment]
So I just included the user's name and email in the login response token.

My suggestion is that you use it with Cookies to persist the logged-in user state.

`exp` refers to `expiration time`, so you can "drop" the user when the time comes.

Let me know if this works for you.

<img width="1199" alt="JWT" src="https://github.com/globe-and-citizen/weve-got-poems/assets/26576201/148fa2b6-e5a8-46d0-8ee0-6829429ad061">

**Comment by hermannleboss** [comment]
I understand, but it's not solving all the needs:

- [ ] Check if the token is still valid
- [ ] Receive user information

---

### Check if the Token Is Still Valid

I know we have the `exp` (expiration time) in the payload, but if we have a system to invalidate the token, the frontend doesn't have any way to know if the token is still valid. To check it, I need to perform an action that is protected and requires a token. Currently, all actions that require a token are POST, PUT, or DELETE requests. The frontend cannot simply create a new resource (e.g., a poem) for a user to check if the token they have is valid or not.

---

### Receive User Information

Regarding this issue, the thing is that we have user information in the payload. However, the payload's role is to verify the user's information on the backend side. It answers the question, "For whom is this token intended?" But for the frontend, the token is just a key. It's not used to directly retrieve user information.

**Comment by hermannleboss** [comment]
And it's not a good idea to decode the token in the frontend . 
To decode the token in the frontend we need to share the JWT secret with the frontend. 

Sharing the JWT secret key with the frontend is a security risk and not a recommended practice for several reasons:

Security Vulnerability: The JWT secret key is a sensitive piece of information that should be kept confidential. Sharing it with the frontend means that anyone with access to the frontend code can potentially misuse the key to create or manipulate tokens. This poses a significant security risk, as malicious actors could generate forged tokens, impersonate users, and gain unauthorized access to resources.

Token Integrity: One of the core purposes of JWTs is to ensure the integrity of data contained within the token. The secret key is used to sign the token, providing a mechanism for the server to verify that the token has not been tampered with. If the secret key is exposed on the frontend, the token's integrity cannot be guaranteed, as any user could alter the token's content.

Authentication and Authorization: The secret key is typically used on the server-side to authenticate and authorize users. By sharing it with the frontend, you bypass the server's control over user authentication and authorization, potentially allowing unauthorized actions or access to protected resources.

Limited Trust: While frontend applications are part of the same system, they should be treated as less trusted components compared to the backend. The frontend is more susceptible to attacks, and trusting it with sensitive keys compromises the security of your entire application.

Scalability and Separation of Concerns: Sharing the secret key blurs the line between the frontend and backend responsibilities. It's a best practice to keep frontend and backend concerns separate for scalability, maintainability, and security. The backend should be the sole authority for verifying and managing JWTs.

**Comment by arnonrdp** [comment]
@hermannleboss, after our meeting did you have any questions?

Do you need me to help you with this?

**Comment by arnonrdp** [comment]
@hermannleboss, this is the lib I usually use in Frontend: https://www.npmjs.com/package/jwt-decode

**Comment by arnonrdp** [comment]
@hermannleboss, let me know if this issue can be closed.
