### ISSUE TITLE
Like and dislike Error

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/weve-got-poems#7]
The user is able to like and dsilike the same poem

A good feature should be: 

**Scenario:** User Interaction with Poem Liking/Disliking

**Given** the user's ability to interact with poems

**When** the user likes or dislikes a poem

**Then** the system should exhibit the following behavior:

1. If the user attempts to like a poem they have already liked, the poem should be unliked.
2. If the user tries to dislike a poem they have previously liked, the poem should be unliked and then disliked.

**Note:** This behavior should be achieved using only a single attribute for tracking the user's interaction status with each poem.

Example: instead of having for each poem like and dislike list of user
He should have likeStatus = [{userId, status }] 
Then we have a function that return the liste of Likes and Dislikes

**Comment by arnonrdp** [comment]
@hermannleboss, I fixed it, let me know if this works now.
